
HOST_IP="localhost"
PORT=7942
MODE="json-rpc"
GIN_MODE="release"
#CONFIG_DIR="/var/lib/signal-cli/"
#ATTACHMENT_DIR="/tmp/"
#AVATAR_DIR="/tmp/"
#LOG_LEVEL="info"
#SWAGGER_USE_HTTPS_AS_PREFERRED_SCHEME="false"
#SWAGGER_IP=$HOST_IP
#SWAGGER_HOST="${HOST_IP}:${PORT}"
#ENABLE_PLUGINS="false"

## The following are not used for JSON-RPC
#AUTO_RECEIVE_SCHEDULE=""
#AUTO_RECEIVE_SCHEDULE_RECEIVE_TIMEOUT=10
#AUTO_RECEIVE_SCHEDULE_IGNORE_ATTACHMENTS="false"
#AUTO_RECEIVE_SCHEDULE_IGNORE_STORIES="false"
#AUTO_RECEIVE_SCHEDULE_SEND_READ_RECEIPTS="false"
