#!/bin/sh

post_upgrade() {

  ## From Debian packages ##

  setcap cap_chown,cap_fowner,cap_sys_chroot,cap_mknod=ep /usr/bin/loolforkit
  setcap cap_sys_admin=ep /usr/bin/loolmount
  

  systemd-sysusers loolwsd.conf
  systemd-tmpfiles --create loolwsd.conf
  chown lool:lool etc/loolwsd/loolwsd.xml
  chmod 640       etc/loolwsd/loolwsd.xml

  chown -R lool:lool opt/lool

  su lool --shell=/bin/sh -c 'set -x; loolwsd-systemplate-setup /opt/lool/systemplate /opt/collaboraoffice'

  systemctl daemon-reload
}

post_install() {

  ## This is adapted from collabora-online-server-nodocker in AUR ##
  ## From Debian packages ##

  # We assume that the LibreOffice to be used is built TDF-style
  # and installs in /opt/collaboraoffice6.4, and that /opt/lool is
  # on the same file system
  mkdir -p opt/lool/child-roots

  cat <<-THEEND
==> 
==>  1) It is expected that this service will be run behind a reverse proxy.
==>     See the Collabora Online documentation regarding built-in SSL.
==> 
==>  2) The username and password must be set in /etc/loolwsd/loolwsd.xml
==>     for the admin console.
==> 
==>  3) In /etc/loolwsd/loolwsd.xml, the host should be set to a value
==>     different than “localhost”.  You may also want to force the
==>     server_name in /etc/loolwsd/loolwsd.xml.
==>
==> 
THEEND

  post_upgrade
}

pre_upgrade() {
	:
}

pre_remove() {
  pre_upgrade
}

post_remove() {
  rm -rf /var/cache/loolwsd
  rm -rf /opt/lool
}
